# Generated by Django 3.2 on 2024-02-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240218_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sell_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('digital', 'Digital'), ('event', 'Event'), ('fundraiser', 'Fundraiser')], default='product', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='cta',
            field=models.CharField(choices=[('buy now', 'Buy Now'), ('contact', 'Contact'), ('shop now', 'Shop Now'), ('Register', 'Register'), ('subscribe', 'Subscribe'), ('donate', 'Donate'), ('get started', 'Get Started')], default='shop now', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('thread', 'Thread'), ('bet', 'Bet'), ('blog', 'Blog'), ('sell', 'Sell'), ('project', 'Project')], default='thread', max_length=50),
        ),
    ]
