# Generated by Django 3.2 on 2024-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240219_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='progress',
            field=models.CharField(choices=[('in progress ', 'In Progress'), ('completed', 'Completed'), ('starting soon', 'Starting Soon')], default='completed', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='project_cta',
            field=models.CharField(choices=[('visit website', 'Visit Website'), ('contact ', 'Contact'), ('learn more', 'Learn More'), ('join us', 'Join Us'), ('donate', 'Donate')], default='visit website', max_length=50),
        ),
    ]
