# Generated by Django 3.2 on 2024-02-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20240223_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_image',
            new_name='comment_image',
        ),
    ]
