# Generated by Django 3.2 on 2024-03-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_post_image_comment_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='topic',
        ),
        migrations.AddField(
            model_name='tag',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('beauty & wellness', 'Beauty & Wellness'), ('hospitality', 'Hospitality'), ('professional services', 'Professional Services'), ('real estate', 'Real Estate'), ('art & culture', 'Art & Culture'), ('sports & fitness', 'Sports & Fitness'), ('events & entertainment', 'Events & Entertainment'), ('public service', 'Public Service'), ('blue collar', 'Blue Collar'), ('non profit', 'Non Profit'), ('manufacturing', 'Manufacturing'), ('telecommunications', 'Telecommunications'), ('engineering', 'Engineering'), ('agriculture', 'Agriculture'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('beauty & wellness', 'Beauty & Wellness'), ('hospitality', 'Hospitality'), ('professional services', 'Professional Services'), ('real estate', 'Real Estate'), ('art & culture', 'Art & Culture'), ('sports & fitness', 'Sports & Fitness'), ('events & entertainment', 'Events & Entertainment'), ('public service', 'Public Service'), ('blue collar', 'Blue Collar'), ('non profit', 'Non Profit'), ('manufacturing', 'Manufacturing'), ('telecommunications', 'Telecommunications'), ('engineering', 'Engineering'), ('agriculture', 'Agriculture'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
    ]
