# Generated by Django 3.2 on 2024-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_is_pinned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sale_price',
            new_name='max_price',
        ),
        migrations.AddField(
            model_name='post',
            name='min_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('beauty & wellness', 'Beauty & Wellness'), ('hospitality', 'Hospitality'), ('professional services', 'Professional Services'), ('Food', 'Food'), ('real estate', 'Real Estate'), ('art & culture', 'Art & Culture'), ('sports & fitness', 'Sports & Fitness'), ('events & entertainment', 'Events & Entertainment'), ('public service', 'Public Service'), ('blue collar', 'Blue Collar'), ('non profit', 'Non Profit'), ('manufacturing', 'Manufacturing'), ('telecommunications', 'Telecommunications'), ('engineering', 'Engineering'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('beauty & wellness', 'Beauty & Wellness'), ('hospitality', 'Hospitality'), ('professional services', 'Professional Services'), ('Food', 'Food'), ('real estate', 'Real Estate'), ('art & culture', 'Art & Culture'), ('sports & fitness', 'Sports & Fitness'), ('events & entertainment', 'Events & Entertainment'), ('public service', 'Public Service'), ('blue collar', 'Blue Collar'), ('non profit', 'Non Profit'), ('manufacturing', 'Manufacturing'), ('telecommunications', 'Telecommunications'), ('engineering', 'Engineering'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
    ]
