# Generated by Django 3.2 on 2024-04-24 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20240403_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='industry',
        ),
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.CharField(default='s', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('gifts', 'Gifts'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('decor', 'Decor')], default='Clothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('thread', 'Thread'), ('product', 'Product'), ('blog', 'Blog'), ('sell', 'Sell'), ('project', 'Project')], default='thread', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='post_tags', to='posts.Tag'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_img/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_img', to='posts.post')),
            ],
        ),
    ]
