# Generated by Django 3.2 on 2024-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20240424_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('gifts', 'Gifts'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('decor', 'Decor'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('gifts', 'Gifts'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('decor', 'Decor'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
    ]
