# Generated by Django 3.2 on 2024-04-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20240429_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_img', to='posts.post'),
        ),
    ]
