# Generated by Django 3.2 on 2024-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_productimage_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('gifts', 'Gifts'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('decor', 'Decor'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='sell_type',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('digital', 'Digital'), ('event', 'Event'), ('fundraiser', 'Fundraiser'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('gifts', 'Gifts'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('decor', 'Decor'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
    ]
