# Generated by Django 3.2 on 2024-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240218_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/default_avatar.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
