# Generated by Django 3.2 on 2024-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='user_tokens',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_img/'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='price_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('beauty & wellness', 'Beauty & Wellness'), ('hospitality', 'Hospitality'), ('professional services', 'Professional Services'), ('Food', 'Food'), ('real estate', 'Real Estate'), ('art & culture', 'Art & Culture'), ('sports & fitness', 'Sports & Fitness'), ('events & entertainment', 'Events & Entertainment'), ('public service', 'Public Service'), ('blue collar', 'Blue Collar'), ('non profit', 'Non Profit'), ('manufacturing', 'Manufacturing'), ('telecommunications', 'Telecommunications'), ('engineering', 'Engineering'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='industry',
            field=models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('beauty & wellness', 'Beauty & Wellness'), ('hospitality', 'Hospitality'), ('professional services', 'Professional Services'), ('Food', 'Food'), ('real estate', 'Real Estate'), ('art & culture', 'Art & Culture'), ('sports & fitness', 'Sports & Fitness'), ('events & entertainment', 'Events & Entertainment'), ('public service', 'Public Service'), ('blue collar', 'Blue Collar'), ('non profit', 'Non Profit'), ('manufacturing', 'Manufacturing'), ('telecommunications', 'Telecommunications'), ('engineering', 'Engineering'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='shop_services', to='shops.Service'),
        ),
        migrations.AddField(
            model_name='shop',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='shop_locations', to='shops.Location'),
        ),
    ]
