# Generated by Django 3.2 on 2024-04-12 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20240403_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('retail', 'Retail'), ('beauty & wellness', 'Beauty & Wellness'), ('hospitality', 'Hospitality'), ('professional services', 'Professional Services'), ('Food', 'Food'), ('real estate', 'Real Estate'), ('art & culture', 'Art & Culture'), ('sports & fitness', 'Sports & Fitness'), ('events & entertainment', 'Events & Entertainment'), ('public service', 'Public Service'), ('blue collar', 'Blue Collar'), ('non profit', 'Non Profit'), ('manufacturing', 'Manufacturing'), ('telecommunications', 'Telecommunications'), ('engineering', 'Engineering'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50)),
                ('about', models.TextField(max_length=10000)),
                ('dis_price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_low',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_up',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_img/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_img', to='shops.product')),
            ],
        ),
    ]
