# Generated by Django 3.2 on 2024-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_auto_20240412_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('category', models.CharField(choices=[('Clothing', 'Clothing'), ('gifts', 'Gifts'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('decor', 'Decor')], default='Clothing', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='about',
            new_name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='small', max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothing', 'Clothing'), ('gifts', 'Gifts'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('decor', 'Decor')], default='Clothing', max_length=50),
        ),
    ]
