# Generated by Django 3.2 on 2024-04-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_auto_20240414_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='headline',
        ),
    ]
