# Generated by Django 3.2 on 2024-04-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_rename_name_product_headline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
