# Generated by Django 3.2 on 2024-04-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20240424_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
