# Generated by Django 3.2 on 2024-02-19 08:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_policy_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
