# Generated by Django 3.2 on 2024-02-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_alter_policy_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='policy',
            name='pol',
            field=models.CharField(choices=[('privacy', 'Privacy'), ('guidelines', 'Guidelines'), ('terms', 'Terms'), ('license', 'License'), ('manifesto', 'Manifesto')], default='privacy', max_length=50),
        ),
    ]
