# Generated by Django 3.2 on 2024-02-17 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=10000)),
                ('gig_type', models.CharField(choices=[('part-time', 'Part-Time'), ('full-time', 'Full-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], default='contract', max_length=50)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('blue collar', 'Blue Collar'), ('real estate', 'Real Estate'), ('energy', 'Energy'), ('public service', 'Public Service'), ('non profit', 'Non Profit'), ('transportation & logistics', 'Transportation & Logistics'), ('telecommunications', 'Telecommunications'), ('media & entertainment', 'Media & Entertainment'), ('construction & engineering', 'Construction & Engineering'), ('agriculture', 'Agriculture'), ('education', 'Education'), ('professional services', 'Professional Services')], default='energy', max_length=50)),
                ('experience', models.CharField(choices=[('entry level', 'Entry Level'), ('mid level', 'Mid Level'), ('senior level', 'Senior Level'), ('no experience', 'No Experience')], default='entry level', max_length=50)),
                ('apply_link', models.URLField(blank=True)),
                ('flagged', models.BooleanField(default=False)),
                ('report_count', models.IntegerField(default=0)),
                ('max_apply', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_posted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1000)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apply_by', to=settings.AUTH_USER_MODEL)),
                ('gig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_gig', to='gigs.gig')),
            ],
        ),
        migrations.CreateModel(
            name='GigApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.gig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gig')},
            },
        ),
    ]
