# Generated by Django 3.2 on 2024-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('delete', 'Delete'), ('fine', 'Fine'), ('keep', 'Keep'), ('bug', 'Bug'), ('follow', 'Follow')], max_length=10),
        ),
    ]
